default_language_version:
    # default language version for each language
    python: python3.8
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-ast
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: debug-statements
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/pycqa/pylint
      rev: 'pylint-2.7.4'
      hooks:
          - id: pylint
            exclude: '[a-zA-Z]*/(migrations)/(.)*'
            args:
                [
                    '--load-plugins=pylint_django',
                    '--django-settings-module=app.settings',
                ]
            additional_dependencies: [pylint_django]
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
