# Generated by Django 3.2 on 2021-04-21 12:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.CharField(default=uuid.UUID('f37afeab-a29b-11eb-8de6-347df658858f'), max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=uuid.UUID('f37afeaa-a29b-11eb-92ca-347df658858f'), max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.UUID('f36f3ed4-a29b-11eb-b891-347df658858f'), max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('type_user', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.CharField(default=uuid.UUID('f37b2683-a29b-11eb-a7bc-347df658858f'), max_length=64, primary_key=True, serialize=False)),
                ('points', models.IntegerField(max_length=1)),
                ('id_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heros_apis.character')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heros_apis.user')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heros_apis.company'),
        ),
    ]
