# Generated by Django 3.2 on 2021-04-21 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heros_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.CharField(default=uuid.UUID('145ddba9-a29c-11eb-9edf-347df658858f'), max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=uuid.UUID('145db57a-a29c-11eb-a261-347df658858f'), max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.CharField(default=uuid.UUID('145ddbaa-a29c-11eb-9732-347df658858f'), max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('145528fd-a29c-11eb-9b5d-347df658858f'), max_length=64, primary_key=True, serialize=False),
        ),
    ]
