# Generated by Django 3.2 on 2021-04-26 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("heros_apis", "0002_auto_20210421_0821"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="type_user",
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="id",
            field=models.CharField(
                default=uuid.UUID("4379953e-a6dc-11eb-a814-b4a9fca157cd"),
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.CharField(
                default=uuid.UUID("4379953d-a6dc-11eb-8d0c-b4a9fca157cd"),
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="id",
            field=models.CharField(
                default=uuid.UUID("4379953f-a6dc-11eb-9600-b4a9fca157cd"),
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("43713239-a6dc-11eb-bcbd-b4a9fca157cd"),
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
